### PR TITLE
20160341_Mohammed Hussin 

### PR DESCRIPTION
**Pull request by Mohammedhussingh**
Adding most repeated value

### CODE REVIEW

**Comment by Mohammedhussingh** [comment]
The array must be integer array according to the assignment word file.Thank
you.

On 29 Nov 2018 22:05, "saifeldeenaziz" <notifications@github.com> wrote:

*@saifeldeenaziz* requested changes on this pull request.

I think you should modify the function to take a string input and parse the
integers by splitting the string using ", " -comma space- as agreed on our
slack channel.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KarimAil/team-20/pull/1#pullrequestreview-179989849>,
or mute the thread

**Comment by saifeldeenaziz** [comment]
The array for this specific function is supposed to be integer, I agree. but the thing is we'll have one input to all the 17 functions and as the assignment states some functions can take character arrays not only integers. 
That's why it was suggested that we all modify our functions to take a string in the format "1, 2, 3" then parse it inside the function as requested per said function.

**Comment by saifeldeenaziz** [comment]
yeah, you're right only 3 functions can take both characters and integers but as per my knowledge you can't take a character input in an integer array so how are you proposing to find a way to transform an integer array? furthermore, I guess if you don't agree about the string input format you should've said so on slack and if you still have other ideas maybe let's discuss it on slack first better than having an argument here.

**Comment by Mohammedhussingh** [comment]
Saifeldeen , sorry I was not online for a while , but the rules of
assignment i think it is almost fixed , and  the way that we upload the
files using it is so time consuming , brows  this link and give me your
opinion ...



https://www.geeksforgeeks.org/different-ways-for-integer-to-string-conversions-in-java/

‫في الخميس، 29 نوفمبر 2018 في 9:53 م تمت كتابة ما يلي بواسطة
‪saifeldeenaziz‬‏ <‪notifications@github.com‬‏>:‬

**Pull request merged**
